env: flex
runtime: custom
service:
resources:
  cpu: .5
  memory_gb: .9
  disk_size_gb: 10
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 20
  cool_down_period_sec: 120 # default value
  cpu_utilization:
    target_utilization: 0.5
